### ISSUE TITLE
Link to content?

### ISSUE THREAD

**Issue by WebFreak001** [sami2020pro/dlang-examples#1]
The website link that is setup on the GitHub (dlang.ir) seems to be broken & the README doesn't say where else the content is. The src directory seems to be very raw.

**Comment by sami2020pro** [comment]
Yes, that's correct :ok_hand:
The project is supposed to be completed in a certain process and soon the website will come up and the project is not ready yet and even some of the codes are problematic or not written.

Another reason is that I got involved in another project and it made things difficult for me!

**Comment by WebFreak001** [comment]
do tell me when it's ready so I can add it to https://github.com/dlang-community/awesome-d

**Comment by sami2020pro** [comment]
I close this issue. When the project is ready, I will re-open this issue and tell you.
